/**
 * This file is generated by scripts/generate-extension-config.mjs.
 * Do not edit it by hand.
 */

(function(root, factory) {
    const api = factory();

    if (typeof module !== "undefined" && module.exports) {
        module.exports = api;
    }

    root.NavioAllowedHosts = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function() {
    "use strict";

    const DOMAIN_SUFFIXES = [
    "google.com",
    "google.co.uk",
    "google.ca",
    "google.com.au",
    "google.de",
    "google.fr",
    "google.es",
    "google.it",
    "google.co.jp",
    "google.co.in",
    "google.com.br",
    "google.ru",
    "google.co.kr",
    "google.com.mx",
    "google.nl",
    "google.pl",
    "google.se",
    "google.ch",
    "google.at",
    "google.be"
];

    function normalizeHost(host) {
        return typeof host === "string" ? host.trim().toLowerCase() : "";
    }

    function isAllowedGoogleHost(host) {
        const normalizedHost = normalizeHost(host);
        if (!normalizedHost) {
            return false;
        }

        return DOMAIN_SUFFIXES.some(function(domain) {
            return normalizedHost === domain || normalizedHost.endsWith("." + domain);
        });
    }

    return {
        DOMAIN_SUFFIXES: DOMAIN_SUFFIXES,
        isAllowedGoogleHost: isAllowedGoogleHost
    };
});
